/**
 * @file    lcd_i2c.c
 * @brief   HD44780 16x2 LCD Driver via PCF8574 I2C Expander (4-bit mode)
 *          Backlight is always ON.
 *
 *          PCF8574 pin mapping:
 *            P0 = RS
 *            P1 = RW (always LOW - write only)
 *            P2 = EN
 *            P3 = Backlight
 *            P4 = D4
 *            P5 = D5
 *            P6 = D6
 *            P7 = D7
 */
#include "lcd_i2c.h"
#include "cmsis_os.h"
#include <string.h>
#include <stdio.h>

/* PCF8574 bit definitions */
#define LCD_RS   0x01
#define LCD_RW   0x02
#define LCD_EN   0x04
#define LCD_BL   0x08   /* Backlight ON */
#define LCD_D4   0x10
#define LCD_D5   0x20
#define LCD_D6   0x40
#define LCD_D7   0x80

static I2C_HandleTypeDef *_hi2c = NULL;
static uint8_t _backlight = LCD_BL;

/* ── Internal helpers ────────────────────────────── */

static void LCD_SendByte(uint8_t data)
{
    HAL_I2C_Master_Transmit(_hi2c, LCD_I2C_ADDR, &data, 1, HAL_MAX_DELAY);
}

static void LCD_Pulse(uint8_t data)
{
    LCD_SendByte(data | LCD_EN);
    osDelay(1);
    LCD_SendByte(data & ~LCD_EN);
    osDelay(1);
}

static void LCD_WriteNibble(uint8_t nibble, uint8_t rs)
{
    uint8_t data = _backlight | rs;
    if (nibble & 0x08) data |= LCD_D7;
    if (nibble & 0x04) data |= LCD_D6;
    if (nibble & 0x02) data |= LCD_D5;
    if (nibble & 0x01) data |= LCD_D4;
    LCD_Pulse(data);
}

static void LCD_Send(uint8_t value, uint8_t rs)
{
    LCD_WriteNibble(value >> 4, rs);    /* High nibble first */
    LCD_WriteNibble(value & 0x0F, rs);  /* Low nibble second */
}

static void LCD_Cmd(uint8_t cmd)
{
    LCD_Send(cmd, 0x00); /* RS = 0 => command register */
    osDelay(2);
}

/* ── Public API ──────────────────────────────────── */

/**
 * @brief  Initialise the LCD in 4-bit mode.
 * @param  hi2c  Pointer to the I2C1 handle (generated by CubeMX).
 */
void LCD_Init(I2C_HandleTypeDef *hi2c)
{
    _hi2c = hi2c;
    osDelay(50); /* Wait for LCD power-up */

    /* Initialisation sequence (datasheet HD44780) */
    LCD_WriteNibble(0x03, 0); osDelay(5);
    LCD_WriteNibble(0x03, 0); osDelay(2);
    LCD_WriteNibble(0x03, 0); osDelay(2);
    LCD_WriteNibble(0x02, 0); osDelay(2); /* Switch to 4-bit mode */

    LCD_Cmd(0x28); /* Function set: 2 lines, 5x8 font */
    LCD_Cmd(0x0C); /* Display ON, cursor OFF, blink OFF */
    LCD_Cmd(0x06); /* Entry mode: cursor moves right */
    LCD_Cmd(0x01); /* Clear display */
    osDelay(5);
}

/**
 * @brief  Clear the LCD display.
 */
void LCD_Clear(void)
{
    LCD_Cmd(0x01);
    osDelay(5);
}

/**
 * @brief  Move cursor to specified position.
 * @param  col  Column (0-15)
 * @param  row  Row (0 or 1)
 */
void LCD_SetCursor(uint8_t col, uint8_t row)
{
    uint8_t rowOffsets[] = {0x00, 0x40};
    LCD_Cmd(0x80 | (col + rowOffsets[row % 2]));
}

/**
 * @brief  Write a single character at the current cursor position.
 * @param  c  Character to display.
 */
void LCD_WriteChar(char c)
{
    LCD_Send((uint8_t)c, LCD_RS); /* RS = 1 => data register */
}

/**
 * @brief  Write a null-terminated string at the current cursor position.
 * @param  str  Pointer to the string.
 */
void LCD_WriteString(const char *str)
{
    while (*str)
        LCD_WriteChar(*str++);
}
